// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: push/push.proto

package push

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Push_PushToKafka_FullMethodName      = "/Push/PushToKafka"
	Push_PushToKafkaDelay_FullMethodName = "/Push/PushToKafkaDelay"
)

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushClient interface {
	PushToKafka(ctx context.Context, in *PushKafkaRequest, opts ...grpc.CallOption) (*PushKafkaResponse, error)
	PushToKafkaDelay(ctx context.Context, in *PushKafkaDelayRequest, opts ...grpc.CallOption) (*PushKafkaDelayResponse, error)
}

type pushClient struct {
	cc grpc.ClientConnInterface
}

func NewPushClient(cc grpc.ClientConnInterface) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) PushToKafka(ctx context.Context, in *PushKafkaRequest, opts ...grpc.CallOption) (*PushKafkaResponse, error) {
	out := new(PushKafkaResponse)
	err := c.cc.Invoke(ctx, Push_PushToKafka_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushClient) PushToKafkaDelay(ctx context.Context, in *PushKafkaDelayRequest, opts ...grpc.CallOption) (*PushKafkaDelayResponse, error) {
	out := new(PushKafkaDelayResponse)
	err := c.cc.Invoke(ctx, Push_PushToKafkaDelay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServer is the server API for Push service.
// All implementations should embed UnimplementedPushServer
// for forward compatibility
type PushServer interface {
	PushToKafka(context.Context, *PushKafkaRequest) (*PushKafkaResponse, error)
	PushToKafkaDelay(context.Context, *PushKafkaDelayRequest) (*PushKafkaDelayResponse, error)
}

// UnimplementedPushServer should be embedded to have forward compatible implementations.
type UnimplementedPushServer struct {
}

func (UnimplementedPushServer) PushToKafka(context.Context, *PushKafkaRequest) (*PushKafkaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToKafka not implemented")
}
func (UnimplementedPushServer) PushToKafkaDelay(context.Context, *PushKafkaDelayRequest) (*PushKafkaDelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushToKafkaDelay not implemented")
}

// UnsafePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServer will
// result in compilation errors.
type UnsafePushServer interface {
	mustEmbedUnimplementedPushServer()
}

func RegisterPushServer(s grpc.ServiceRegistrar, srv PushServer) {
	s.RegisterService(&Push_ServiceDesc, srv)
}

func _Push_PushToKafka_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushKafkaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).PushToKafka(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_PushToKafka_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).PushToKafka(ctx, req.(*PushKafkaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Push_PushToKafkaDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushKafkaDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).PushToKafkaDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_PushToKafkaDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).PushToKafkaDelay(ctx, req.(*PushKafkaDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Push_ServiceDesc is the grpc.ServiceDesc for Push service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Push_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Push",
	HandlerType: (*PushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToKafka",
			Handler:    _Push_PushToKafka_Handler,
		},
		{
			MethodName: "PushToKafkaDelay",
			Handler:    _Push_PushToKafkaDelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push/push.proto",
}
