// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: push/push.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelayEnum int32

const (
	DelayEnum__DelayEnumUnknown DelayEnum = 0
	DelayEnum_DelayEnum1m       DelayEnum = 1
	DelayEnum_DelayEnum3m       DelayEnum = 2
	DelayEnum_DelayEnum10m      DelayEnum = 3
	DelayEnum_DelayEnum15m      DelayEnum = 4
	DelayEnum_DelayEnum30m      DelayEnum = 5
)

// Enum value maps for DelayEnum.
var (
	DelayEnum_name = map[int32]string{
		0: "_DelayEnumUnknown",
		1: "DelayEnum1m",
		2: "DelayEnum3m",
		3: "DelayEnum10m",
		4: "DelayEnum15m",
		5: "DelayEnum30m",
	}
	DelayEnum_value = map[string]int32{
		"_DelayEnumUnknown": 0,
		"DelayEnum1m":       1,
		"DelayEnum3m":       2,
		"DelayEnum10m":      3,
		"DelayEnum15m":      4,
		"DelayEnum30m":      5,
	}
)

func (x DelayEnum) Enum() *DelayEnum {
	p := new(DelayEnum)
	*p = x
	return p
}

func (x DelayEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelayEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[0].Descriptor()
}

func (DelayEnum) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[0]
}

func (x DelayEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelayEnum.Descriptor instead.
func (DelayEnum) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

type PushKafkaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PushKafkaRequest) Reset() {
	*x = PushKafkaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushKafkaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushKafkaRequest) ProtoMessage() {}

func (x *PushKafkaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushKafkaRequest.ProtoReflect.Descriptor instead.
func (*PushKafkaRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushKafkaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PushKafkaRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PushKafkaRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PushKafkaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PushKafkaResponse) Reset() {
	*x = PushKafkaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushKafkaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushKafkaResponse) ProtoMessage() {}

func (x *PushKafkaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushKafkaResponse.ProtoReflect.Descriptor instead.
func (*PushKafkaResponse) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushKafkaResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PushKafkaDelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic string    `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data  string    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Delay DelayEnum `protobuf:"varint,4,opt,name=delay,proto3,enum=DelayEnum" json:"delay,omitempty"`
}

func (x *PushKafkaDelayRequest) Reset() {
	*x = PushKafkaDelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushKafkaDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushKafkaDelayRequest) ProtoMessage() {}

func (x *PushKafkaDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushKafkaDelayRequest.ProtoReflect.Descriptor instead.
func (*PushKafkaDelayRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushKafkaDelayRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PushKafkaDelayRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PushKafkaDelayRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PushKafkaDelayRequest) GetDelay() DelayEnum {
	if x != nil {
		return x.Delay
	}
	return DelayEnum__DelayEnumUnknown
}

type PushKafkaDelayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PushKafkaDelayResponse) Reset() {
	*x = PushKafkaDelayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushKafkaDelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushKafkaDelayResponse) ProtoMessage() {}

func (x *PushKafkaDelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushKafkaDelayResponse.ProtoReflect.Descriptor instead.
func (*PushKafkaDelayResponse) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

func (x *PushKafkaDelayResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_push_push_proto protoreflect.FileDescriptor

var file_push_push_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4c, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x23, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x73, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x4b, 0x61, 0x66, 0x6b,
	0x61, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x28, 0x0a, 0x16, 0x50, 0x75, 0x73,
	0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x2a, 0x7a, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x15, 0x0a, 0x11, 0x5f, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x61, 0x79,
	0x45, 0x6e, 0x75, 0x6d, 0x31, 0x6d, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x45, 0x6e, 0x75, 0x6d, 0x33, 0x6d, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x30, 0x6d, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x35, 0x6d, 0x10, 0x04, 0x12, 0x10, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x45, 0x6e, 0x75, 0x6d, 0x33, 0x30, 0x6d, 0x10, 0x05, 0x32,
	0x85, 0x01, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x36, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x12, 0x11, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4b, 0x61,
	0x66, 0x6b, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x12, 0x16, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x70, 0x75, 0x73, 0x68, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData = file_push_push_proto_rawDesc
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_push_proto_rawDescData)
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_push_proto_goTypes = []interface{}{
	(DelayEnum)(0),                 // 0: DelayEnum
	(*PushKafkaRequest)(nil),       // 1: PushKafkaRequest
	(*PushKafkaResponse)(nil),      // 2: PushKafkaResponse
	(*PushKafkaDelayRequest)(nil),  // 3: PushKafkaDelayRequest
	(*PushKafkaDelayResponse)(nil), // 4: PushKafkaDelayResponse
}
var file_push_push_proto_depIdxs = []int32{
	0, // 0: PushKafkaDelayRequest.delay:type_name -> DelayEnum
	1, // 1: Push.PushToKafka:input_type -> PushKafkaRequest
	3, // 2: Push.PushToKafkaDelay:input_type -> PushKafkaDelayRequest
	2, // 3: Push.PushToKafka:output_type -> PushKafkaResponse
	4, // 4: Push.PushToKafkaDelay:output_type -> PushKafkaDelayResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushKafkaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushKafkaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushKafkaDelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushKafkaDelayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_push_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		EnumInfos:         file_push_push_proto_enumTypes,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_rawDesc = nil
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
